name: discord-bot-development
services:
  host:
    image: grl-bot-app
    build:
      context: .
      dockerfile: ./src/ConsoleApp/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
    restart: unless-stopped
    networks:
      - grl-bot-network
    depends_on:
      - grl-bot-db
  
  grl-bot-db:
    image: postgres:15-alpine
    container_name: grl-bot-db
    environment:
      - POSTGRES_DB=grl-bot
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pwd
    volumes:
      - grl_bot_db_data:/data/db
    ports:
      - "5555:5432"   # Use localhost:5555 to connect from data sources
    restart: unless-stopped
    networks:
      - grl-bot-network

networks:
  grl-bot-network:
    name: grl-bot-network
    driver: bridge

volumes:
  grl_bot_db_data:
    driver: local
