services:
  host:
    image: grl-bot:<IMAGE_TAG>
    container_name: grl-bot
    environment:
      - DOTNET_ENVIRONMENT=Production
    restart: unless-stopped
    networks:
      - grl-bot-network
    depends_on:
      - grl-bot-db

  grl-bot-db:
    image: postgres:15-alpine
    container_name: grl-bot-db
    environment:
      - POSTGRES_DB=<POSTGRES_DB>
      - POSTGRES_USER=<POSTGRES_USER>
      - POSTGRES_PASSWORD=<POSTGRES_PASSWORD>
    volumes:
      - grl_bot_db_data:/data/db
    ports:
      - "5555:5432"
    restart: unless-stopped
    networks:
      - grl-bot-network

networks:
  grl-bot-network:
    name: grl-bot-network
    driver: bridge

volumes:
  grl_bot_db_data:
    driver: local